### ISSUE TITLE
Any plans for webpack 5?

### ISSUE THREAD

**Issue by scottohara** [JS-DevTools/coverage-istanbul-loader#8]
Hi, a refugee from https://github.com/webpack-contrib/istanbul-instrumenter-loader here...

The `istanbul-instrumenter-loader` project now appears to be archived/abandoned by it's maintainers, so the likelihood of it being updated to support webpack v5 seems remote at this point.

I was already considering replacing `istanbul-instrumenter-loader` with `coverage-istanbul-loader`, because the last published release (`istanbul-instrumenter-loader@3.0.1`)  uses a very old version of `instanbul-lib-instrument` that doesn't support some newer ES2019 language features like [optional catch bindings](https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/96).

However it is not immediately clear whether `coverage-istanbul-loader` supports webpack 5 yet or not? (`package.json` file has `webpack: ^4.43.0` in `devDependencies`)

If it does already support webpack 5, that's great. If not, are there any plans to add webpack 5 support?

There doesn't appear to be a lot of recent activity in this project, so I'm wondering whether this project is also at risk of being abandoned?

**Comment by scottohara** [comment]
For what its worth, I have confirmed that this does indeed work with webpack 5.

**Comment by eelkram** [comment]
https://www.npmjs.com/package/@ephesoft/webpack.istanbul.loader
